/**
 * src/demoData.js
 * Fallback sample data shown when backend is unreachable.
 */

export const DEMO_GRADES = [
  {
    grade_id: "g_001",
    student_id: "STU_1042",
    exam_id: "EXAM_DEMO",
    question_number: 1,
    ocr_text: "E = mc² is Einstein's mass-energy equivalence formula. The energy of a body is equal to its mass multiplied by the speed of light squared.",
    rubric_id: "r_001",
    criterion_scores: [
      { criterion_id: "c1", awarded_points: 5, justification: "Correct formula stated and identified." },
      { criterion_id: "c2", awarded_points: 4, justification: "Good explanation but missing relativistic context." },
    ],
    total_awarded: 9,
    total_possible: 10,
    overall_justification: "Strong answer with minor omission.",
    status: "pending",
    plagiarism_flag: false,
    plagiarism_similarity: 0.0,
    graded_at: "2024-11-12T10:23:00Z",
    reviewed_by: null,
    ta_override_score: null,
    ta_override_note: null,
  },
  {
    grade_id: "g_002",
    student_id: "STU_2031",
    exam_id: "EXAM_DEMO",
    question_number: 1,
    ocr_text: "E equals mc squared. Energy equals mass times the speed of light to the second power. This is used in nuclear physics.",
    rubric_id: "r_001",
    criterion_scores: [
      { criterion_id: "c1", awarded_points: 4, justification: "Formula correct but notation informal." },
      { criterion_id: "c2", awarded_points: 3, justification: "Basic explanation provided." },
    ],
    total_awarded: 7,
    total_possible: 10,
    overall_justification: "Acceptable but surface-level.",
    status: "ai_graded",
    plagiarism_flag: false,
    plagiarism_similarity: 0.12,
    graded_at: "2024-11-12T10:24:10Z",
    reviewed_by: null,
    ta_override_score: null,
    ta_override_note: null,
  },
  {
    grade_id: "g_003",
    student_id: "STU_3017",
    exam_id: "EXAM_DEMO",
    question_number: 2,
    ocr_text: "Newton's first law states that an object at rest stays at rest unless acted upon by an external force.",
    rubric_id: "r_002",
    criterion_scores: [
      { criterion_id: "c3", awarded_points: 5, justification: "Law correctly stated." },
      { criterion_id: "c4", awarded_points: 5, justification: "Clear and accurate explanation." },
    ],
    total_awarded: 10,
    total_possible: 10,
    overall_justification: "Perfect answer.",
    status: "approved",
    plagiarism_flag: false,
    plagiarism_similarity: 0.0,
    graded_at: "2024-11-12T10:25:00Z",
    reviewed_by: "TA_001",
    ta_override_score: null,
    ta_override_note: null,
  },
  {
    grade_id: "g_004",
    student_id: "STU_1042",
    exam_id: "EXAM_DEMO",
    question_number: 2,
    ocr_text: "Newton's first law: an object moves at rest or constant velocity unless a force acts on it.",
    rubric_id: "r_002",
    criterion_scores: [
      { criterion_id: "c3", awarded_points: 4, justification: "Minor inaccuracy in phrasing." },
      { criterion_id: "c4", awarded_points: 3, justification: "Explanation is incomplete." },
    ],
    total_awarded: 7,
    total_possible: 10,
    overall_justification: "Good but imprecise.",
    status: "overridden",
    plagiarism_flag: false,
    plagiarism_similarity: 0.0,
    graded_at: "2024-11-12T10:26:00Z",
    reviewed_by: "TA_001",
    ta_override_score: 8,
    ta_override_note: "Partial credit for understanding demonstrated in context.",
  },
  {
    grade_id: "g_005",
    student_id: "STU_4099",
    exam_id: "EXAM_DEMO",
    question_number: 1,
    ocr_text: "E = mc². Energy equals mass times the speed of light squared. This is Einstein's famous equation.",
    rubric_id: "r_001",
    criterion_scores: [
      { criterion_id: "c1", awarded_points: 5, justification: "Correct formula." },
      { criterion_id: "c2", awarded_points: 4, justification: "Good explanation." },
    ],
    total_awarded: 9,
    total_possible: 10,
    overall_justification: "Near-identical to g_001 — potential plagiarism.",
    status: "flagged",
    plagiarism_flag: true,
    plagiarism_similarity: 0.87,
    graded_at: "2024-11-12T10:27:00Z",
    reviewed_by: null,
    ta_override_score: null,
    ta_override_note: null,
  },
];

export const DEMO_PENDING = DEMO_GRADES.filter((g) => g.status === "pending" || g.status === "ai_graded");

export const DEMO_PLAGIARISM = DEMO_GRADES.filter((g) => g.plagiarism_flag);

export const DEMO_JOB = {
  job_id: "JOB_DEMO",
  exam_id: "EXAM_DEMO",
  status: "completed",
  progress: 100,
  message: "All 5 answer sheets graded successfully.",
  created_at: "2024-11-12T10:20:00Z",
  updated_at: "2024-11-12T10:27:00Z",
  logs: [
    "Job started.",
    "PDF parsing complete: 5 pages.",
    "OCR extraction complete.",
    "AI grading in progress…",
    "Plagiarism check complete.",
    "Job finished.",
  ],
};